repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
    - id: codespell
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
    -   id: markdownlint
